export type FormulaEntry = {
  name: string;
  formula: string;
  use: string;
  example?: string;
};

export const FORMULAS: Record<string, FormulaEntry[]> = {
  // ── Ages 13/14 — Explorers / Pioneers ───────────────────────────────────────
  'age13-algebra': [
    { name: 'Substitution',      formula: 'Replace the letter with its value',     use: 'Evaluate an expression for a given x',                example: '3x + 5, x = 4 → 3(4) + 5 = 17' },
    { name: 'Like Terms',        formula: 'Add coefficients of the same letter',   use: 'Simplify by grouping x with x, numbers with numbers', example: '5x + 2x = 7x' },
    { name: 'Expand Bracket',    formula: 'a(b + c) = ab + ac',                    use: 'Multiply every term inside by the term outside',      example: '3(2x + 4) = 6x + 12' },
    { name: 'Expand Double',     formula: '(x + a)(x + b) = x² + (a+b)x + ab',     use: 'FOIL: First, Outer, Inner, Last',                     example: '(x+2)(x+3) = x² + 5x + 6' },
    { name: 'Common Factor',     formula: 'ab + ac = a(b + c)',                    use: 'Take out the highest common factor',                  example: '6x + 9 = 3(2x + 3)' },
    { name: 'Solve Linear',      formula: 'Inverse operations, reverse order',     use: 'Undo + / − first, then × / ÷',                       example: '3x + 5 = 20 → x = 5' },
  ],
  'age13-geometry': [
    { name: 'Pythagoras',        formula: 'c² = a² + b²',                          use: 'Find a side of a right-angled triangle',        example: '3² + 4² = 5²' },
    { name: 'Find a Shorter Side', formula: 'a² = c² − b²',                         use: 'When the hypotenuse is known',                  example: '√(13² − 5²) = 12' },
    { name: 'Triangle Angle Sum', formula: 'Angles in a triangle = 180°',           use: 'Find a missing angle' },
    { name: 'Angles on a Line',  formula: 'Sum = 180°',                            use: 'Two angles on a straight line' },
    { name: 'Angles at a Point', formula: 'Sum = 360°',                            use: 'Angles meeting at a point' },
    { name: 'Corresponding/Alternate', formula: 'Equal on parallel lines',         use: 'F-shape and Z-shape angles are equal' },
    { name: 'Co-interior',       formula: 'Sum = 180° on parallel lines',          use: 'C-shape (allied) angles' },
    { name: 'Exterior Angle',    formula: '= sum of two opposite interior angles', use: 'Exterior angle of a triangle' },
    { name: 'Isosceles',         formula: 'Two equal base angles',                 use: 'Base = (180 − apex) ÷ 2' },
  ],
  'age13-graphs': [
    { name: 'Gradient',          formula: 'm = (y₂ − y₁)/(x₂ − x₁)',               use: 'Steepness = rise ÷ run' },
    { name: 'Line Equation',     formula: 'y = mx + c',                            use: 'm = gradient, c = y-intercept' },
    { name: 'y-Intercept',       formula: 'Set x = 0 → (0, c)',                     use: 'Where the line crosses the y-axis' },
    { name: 'x-Intercept',       formula: 'Set y = 0, solve for x',                use: 'Where the line crosses the x-axis' },
    { name: 'Parallel Lines',    formula: 'Same gradient (m)',                      use: 'Parallel lines never meet' },
    { name: 'Midpoint',          formula: '((x₁+x₂)/2, (y₁+y₂)/2)',                use: 'Average of the two endpoints' },
  ],
  'age13-numbers': [
    { name: 'Adding Negatives',  formula: '− (−n) = + n',                          use: 'Two minus signs make a plus',      example: '5 − (−3) = 8' },
    { name: 'Sign Rules (×÷)',   formula: '(−)(−)=+,  (−)(+)=−',                   use: 'Multiplying/dividing integers' },
    { name: 'BODMAS',            formula: 'Brackets, Orders, ÷×, +−',              use: 'Order of operations',              example: '2 + 3 × 4 = 14' },
    { name: 'HCF',               formula: 'Highest Common Factor',                 use: 'Biggest number dividing both' },
    { name: 'LCM',               formula: 'a × b ÷ HCF',                           use: 'Lowest Common Multiple',           example: 'LCM(12,18) = 36' },
    { name: 'Square & Root',     formula: 'n² = n×n;  √(n²) = n',                  use: 'Squaring and its inverse' },
    { name: 'Prime',             formula: 'Exactly two factors (1 & itself)',      use: '2, 3, 5, 7, 11 …  (1 is not prime)' },
  ],
  'age13-proportion': [
    { name: 'Share in a Ratio',  formula: 'one part = total ÷ sum of parts',       use: 'Then multiply by each share',      example: 'R60 in 2:1 → R40 : R20' },
    { name: 'Simplify Ratio',    formula: 'Divide both parts by the HCF',          use: '12 : 18 = 2 : 3' },
    { name: 'Unit Rate',         formula: 'total ÷ quantity',                      use: 'Cost or speed per unit' },
    { name: 'Percentage of',     formula: '(x/100) × N',                           use: '"of" means multiply',              example: '25% of 80 = 20' },
    { name: 'Percentage Change', formula: 'find x% of N, then add/subtract',       use: 'Increase or decrease a price' },
    { name: 'Scale',             formula: 'real = map distance × scale',           use: 'Maps and models' },
  ],
  'age13-data': [
    { name: 'Probability',       formula: 'P = favourable ÷ total',                use: 'Single event; simplify the fraction' },
    { name: 'Complement',        formula: "P(not A) = 1 − P(A)",                   use: 'Probability an event does NOT happen' },
    { name: 'Independent (AND)', formula: 'P(A and B) = P(A) × P(B)',              use: 'Multiply for independent events' },
    { name: 'Mean',              formula: 'sum ÷ number of values',                use: 'The average' },
    { name: 'Median',            formula: 'Middle value when sorted',              use: 'Sort first; even count → average the two middle' },
    { name: 'Mode',              formula: 'Most frequent value',                   use: 'Can be none, one, or several' },
    { name: 'Range',             formula: 'largest − smallest',                    use: 'Measures spread' },
    { name: 'IQR',               formula: 'Q3 − Q1',                               use: 'Spread of the middle 50%' },
  ],
  'age14-exponents': [
    { name: 'Product Law',       formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ',          use: 'Same base, multiplying → add powers',  example: 'x³ × x⁴ = x⁷' },
    { name: 'Quotient Law',      formula: 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ',          use: 'Same base, dividing → subtract powers', example: 'x⁷ ÷ x³ = x⁴' },
    { name: 'Power Law',         formula: '(aᵐ)ⁿ = aᵐⁿ',             use: 'Power of a power → multiply powers',    example: '(x³)² = x⁶' },
    { name: 'Zero Exponent',     formula: 'a⁰ = 1',                   use: 'Any non-zero base to the power 0',      example: '5⁰ = 1' },
    { name: 'Negative Exponent', formula: 'a⁻ⁿ = 1/aⁿ',              use: 'Negative power → reciprocal',           example: '2⁻² = 1/4' },
    { name: 'Scientific Notation', formula: 'a × 10ⁿ,  1 ≤ a < 10',   use: 'Write very large or small numbers',     example: '45 000 = 4.5 × 10⁴' },
  ],
  'age15-functions': [
    { name: 'Function Notation',   formula: 'f(x) — substitute x into the rule',        use: 'Evaluate f(3) by replacing every x with 3' },
    { name: 'Composite Function',  formula: 'fg(x) = f(g(x))',                           use: 'Apply g first (inner), then f (outer)',       example: 'f(x)=2x, g(x)=x+1 → fg(3) = f(4) = 8' },
    { name: 'Inverse Function',    formula: 'Let y=f(x), swap x & y, solve for y',       use: 'Undoes the original function',                example: 'f(x)=3x+1 → f⁻¹(x)=(x−1)/3' },
    { name: 'Domain',              formula: 'All valid input values (x)',                 use: 'Exclude values that cause division by 0 or √negative' },
    { name: 'Range',               formula: 'All possible output values f(x)',            use: 'Read from graph or substitute domain limits' },
    { name: 'Translation',         formula: 'y = f(x−h) + k → shift right h, up k',     use: 'Horizontal shift is opposite sign to h',     example: 'y=(x−3)²+2 → right 3, up 2' },
    { name: 'y-intercept of line', formula: 'y = mx + c: c is y-intercept',             use: 'Set x = 0 to find where line crosses y-axis' },
    { name: 'Gradient',            formula: 'm = (y₂−y₁)/(x₂−x₁)',                     use: 'Rate of change; positive = uphill left→right' },
  ],
  'age15-matrices': [
    { name: 'Matrix Multiplication', formula: '[a b][e f] → (ae+bg, af+bh) / (ce+dg, cf+dh)\n[c d][g h]', use: 'Row × Column dot products', example: '2×2 result from two 2×2 matrices' },
    { name: 'Determinant',           formula: 'det[a b / c d] = ad − bc',               use: 'Check if matrix is invertible (det ≠ 0)',    example: 'det[3 1 / 2 4] = 12−2 = 10' },
    { name: 'Reflection y=x',        formula: '(x, y) → (y, x)',                        use: 'Swap coordinates',                           example: '(3,5) → (5,3)' },
    { name: 'Reflection x-axis',     formula: '(x, y) → (x, −y)',                       use: 'Negate y-coordinate' },
    { name: 'Reflection y-axis',     formula: '(x, y) → (−x, y)',                       use: 'Negate x-coordinate' },
    { name: 'Rotation 90° CW',       formula: '(x, y) → (y, −x)',                       use: 'Clockwise about origin' },
    { name: 'Rotation 90° CCW',      formula: '(x, y) → (−y, x)',                      use: 'Anticlockwise about origin' },
    { name: 'Rotation 180°',         formula: '(x, y) → (−x, −y)',                      use: 'Half turn about origin' },
    { name: 'Enlargement',           formula: '(x, y) → (kx, ky)',                      use: 'Scale factor k from origin',                 example: 'SF=3: (2,4)→(6,12)' },
    { name: 'Area after Enlargement',formula: 'New area = k² × original area',          use: 'Area scales by square of length scale factor' },
  ],
  'age15-numbers': [
    { name: 'Simplify Surd',         formula: '√(a²b) = a√b',            use: 'When a perfect square factor exists inside the root', example: '√50 = √(25×2) = 5√2' },
    { name: 'Rationalise Denominator',formula: '1/√b = √b/b',            use: 'Remove surds from the denominator',                   example: '1/√3 = √3/3' },
    { name: 'Multiplication Law',    formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ',          use: 'Same base, multiplying',                             example: 'x³ × x⁴ = x⁷' },
    { name: 'Division Law',          formula: 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ',          use: 'Same base, dividing',                                example: 'y⁶ ÷ y² = y⁴' },
    { name: 'Power Law',             formula: '(aᵐ)ⁿ = aᵐⁿ',             use: 'Power raised to a power',                            example: '(x²)³ = x⁶' },
    { name: 'Negative Exponent',     formula: 'a⁻ⁿ = 1/aⁿ',              use: 'Any negative exponent means reciprocal',             example: 'x⁻² = 1/x²' },
    { name: 'Arithmetic nth Term',   formula: 'Tₙ = a + (n−1)d',         use: 'Arithmetic sequence: a = first term, d = common difference', example: 'a=3, d=4 → T5 = 3+4×4 = 19' },
    { name: 'Geometric nth Term',    formula: 'Tₙ = a × rⁿ⁻¹',          use: 'Geometric sequence: r = common ratio',               example: 'a=2, r=3 → T4 = 2×3³ = 54' },
    { name: 'Arithmetic Sum',        formula: 'Sₙ = n/2(2a + (n−1)d)',   use: 'Sum of first n terms of arithmetic sequence',        example: 'a=1, d=2, n=5 → S5 = 5/2(2+8) = 25' },
    { name: 'Log Definition',        formula: 'logₐ(x) = n ⟺ aⁿ = x',  use: 'Convert between log and exponential form',           example: 'log₂(8) = 3 because 2³ = 8' },
    { name: 'Log Product Law',       formula: 'log(mn) = log(m) + log(n)',use: 'Combine two logs with the same base',               example: 'log(6) = log(2) + log(3)' },
    { name: 'Log Quotient Law',      formula: 'log(m/n) = log(m) − log(n)',use: 'Subtract logs when dividing arguments' },
    { name: 'Log Power Law',         formula: 'log(mⁿ) = n·log(m)',      use: 'Bring the power to the front as a coefficient',     example: 'log(x³) = 3·log(x)' },
  ],
  'age15-algebra': [
    { name: 'Quadratic Formula', formula: 'x = (−b ± √(b²−4ac)) / 2a', use: 'Solve any quadratic ax²+bx+c = 0', example: 'x²+5x+6: a=1, b=5, c=6' },
    { name: 'Discriminant', formula: 'Δ = b²−4ac', use: 'Δ>0: 2 real roots | Δ=0: 1 root | Δ<0: no real roots', example: 'x²+2x+1: Δ=4−4=0 (one root)' },
    { name: 'Difference of Squares', formula: 'a²−b² = (a+b)(a−b)', use: 'Factorise expressions with two perfect squares', example: 'x²−9 = (x+3)(x−3)' },
  ],
  'age15-geometry': [
    { name: 'Distance Formula',     formula: 'd = √((x₂−x₁)² + (y₂−y₁)²)',  use: 'Find distance between two points',                  example: 'd from (0,0) to (3,4) = 5' },
    { name: 'Midpoint Formula',     formula: 'M = ((x₁+x₂)/2, (y₁+y₂)/2)',   use: 'Find the middle point of a segment' },
    { name: 'Gradient',             formula: 'm = (y₂−y₁) / (x₂−x₁)',        use: 'Slope of a line through two points' },
    { name: 'Angle at Centre',      formula: '∠centre = 2 × ∠circumference',  use: 'Same arc, angle at centre is double' },
    { name: 'Thales Theorem',       formula: 'Angle in semicircle = 90°',      use: 'Diameter as chord → right angle at circumference' },
    { name: 'Cyclic Quad',          formula: '∠A + ∠C = 180°',               use: 'Opposite angles of a cyclic quadrilateral are supplementary' },
    { name: 'Tangent-Chord Angle',  formula: '∠ tangent-chord = ∠ alternate segment', use: 'Tangent-chord angle equals angle in alternate segment' },
    { name: 'Same Segment',         formula: 'Angles on same arc, same side = equal', use: 'Same segment theorem' },
    { name: 'Radius ⊥ Tangent',    formula: 'Radius ⊥ tangent at point of contact',  use: 'Angle between radius and tangent is always 90°' },
    { name: 'Equal Tangents',       formula: 'Tangents from external point are equal', use: 'Two tangents from same external point have equal length', example: 'A outside circle: AB = AC if B,C are contact points' },
    { name: 'Equal Chords',         formula: 'Equal chords are equidistant from centre', use: 'If AB = CD then distance from O to AB = distance from O to CD' },
    { name: 'Scale Factor',         formula: 'SF = larger side / smaller side', use: 'Similar triangles: multiply all sides by SF' },
    { name: 'Vector Magnitude',     formula: '|v| = √(x² + y²)',              use: 'Length of a vector (x, y)',                         example: '|(3,4)| = 5' },
    { name: 'Vector Addition',      formula: 'a + b = (x₁+x₂, y₁+y₂)',      use: 'Add corresponding components' },
    { name: 'Scalar Multiplication',formula: 'kv = (kx, ky)',                 use: 'Multiply every component by the scalar k' },
  ],
  'age15-trig': [
    { name: 'SOH',                  formula: 'sin(θ) = Opposite / Hypotenuse',         use: 'Right-angle triangles only' },
    { name: 'CAH',                  formula: 'cos(θ) = Adjacent / Hypotenuse',         use: 'Right-angle triangles only' },
    { name: 'TOA',                  formula: 'tan(θ) = Opposite / Adjacent',           use: 'Right-angle triangles only' },
    { name: 'Sine Rule',            formula: 'a/sin(A) = b/sin(B) = c/sin(C)',         use: '2 angles + 1 side, or 2 sides + non-included angle' },
    { name: 'Cosine Rule (side)',   formula: 'c² = a²+b²−2ab·cos(C)',                 use: '2 sides + included angle → find third side' },
    { name: 'Cosine Rule (angle)',  formula: 'cos(A) = (b²+c²−a²) / 2bc',             use: '3 sides known → find an angle' },
    { name: 'Exact Values',         formula: 'sin30=½  sin45=√2/2  sin60=√3/2',       use: 'Non-calculator trig — memorise these' },
    { name: 'Bearings',             formula: '3-digit clockwise from North (000°–359°)', use: 'Back bearing = forward bearing ± 180°',         example: 'Bearing 065° → back bearing 245°' },
    { name: '3D Pythagoras',        formula: 'd = √(l² + w² + h²)',                   use: 'Space diagonal of a cuboid',                    example: '3×4×5 cuboid: d = √(9+16+25) = √50' },
    { name: 'Angle to Plane',       formula: 'tan(θ) = height / base diagonal',       use: 'Angle between slant line and horizontal plane' },
  ],
  'age15-stats': [
    { name: 'Mean', formula: 'x̄ = Σx / n', use: 'Sum of all values divided by count' },
    { name: 'Median', formula: 'Position = (n+1)/2', use: 'Middle value of sorted data' },
    { name: 'IQR', formula: 'IQR = Q3 − Q1', use: 'Spread of the middle 50% of data' },
    { name: 'Outlier Test', formula: 'Outlier if < Q1−1.5×IQR  or  > Q3+1.5×IQR', use: 'Identify extreme values' },
  ],
  'age15-prob': [
    { name: 'Addition Rule', formula: 'P(A∪B) = P(A) + P(B) − P(A∩B)', use: 'Probability of A or B (or both)' },
    { name: 'Complement Rule', formula: "P(A') = 1 − P(A)", use: 'Probability of event NOT happening' },
    { name: 'Compound Growth', formula: 'A = P(1 + r/100)ⁿ', use: 'Investment growing at r% per year for n years', example: 'R1000 at 10% for 3 years: A = 1000(1.1)³' },
    { name: 'Compound Decay', formula: 'A = P(1 − r/100)ⁿ', use: 'Asset depreciating at r% per year', example: 'Car R50000 at 15% for 2 years' },
  ],

  // ── Age 16 ─────────────────────────────────────────────────────────────────

  'age16-trig2': [
    { name: 'Pythagorean Identity',  formula: 'sin²θ + cos²θ = 1',                          use: 'Find sin, cos, or tan when one ratio is known',         example: 'sin θ=3/5 → cos²θ=1−9/25=16/25' },
    { name: 'Quotient Identity',     formula: 'tan θ = sin θ / cos θ',                       use: 'Find tan from sin and cos',                             example: 'sin=3/5, cos=4/5 → tan=3/4' },
    { name: 'Double Angle (sin)',    formula: 'sin 2x = 2 sin x cos x',                      use: 'Expand or simplify expressions with sin of a double angle', example: 'sin 60° = 2·sin 30°·cos 30° = √3/2' },
    { name: 'Double Angle (cos 1)',  formula: 'cos 2x = cos²x − sin²x',                      use: 'Simplify cos²x − sin²x to a single term' },
    { name: 'Double Angle (cos 2)',  formula: 'cos 2x = 1 − 2sin²x',                         use: 'When you need to eliminate cos²x using the Pythagorean identity' },
    { name: 'Double Angle (cos 3)',  formula: 'cos 2x = 2cos²x − 1',                         use: 'When you need to eliminate sin²x using the Pythagorean identity' },
    { name: 'CAST Diagram',         formula: 'Q1: All positive | Q2: Sin | Q3: Tan | Q4: Cos', use: 'Determine which quadrant(s) give the correct sign for a trig ratio', example: 'sin negative → Q3 and Q4' },
    { name: 'Trig Equations (Q2)',   formula: 'Q2 angle = 180° − ref angle',                 use: 'Second solution for sin positive (Q1 & Q2)',            example: 'sin θ=1/2, ref=30° → Q2: 180°−30°=150°' },
    { name: 'Trig Equations (Q3)',   formula: 'Q3 angle = 180° + ref angle',                 use: 'Second solution for tan positive (Q1 & Q3)',            example: 'tan θ=1, ref=45° → Q3: 180°+45°=225°' },
    { name: 'Trig Equations (Q4)',   formula: 'Q4 angle = 360° − ref angle',                 use: 'Second solution for cos positive (Q1 & Q4)',            example: 'cos θ=1/2, ref=60° → Q4: 360°−60°=300°' },
    { name: 'Exact Values (degrees)', formula: 'sin 30°=1/2  cos 30°=√3/2  tan 30°=√3/3\nsin 45°=√2/2  cos 45°=√2/2  tan 45°=1\nsin 60°=√3/2  cos 60°=1/2  tan 60°=√3', use: 'No-calculator trig — memorise the 30-45-60 triangle values' },
    { name: 'Radian Definition',      formula: '180° = π radians  (exact)',                   use: 'The fundamental conversion between degrees and radians' },
    { name: 'Degrees → Radians',      formula: 'radians = degrees × π/180',                   use: 'Multiply degrees by π/180 to convert',                  example: '60° × π/180 = π/3' },
    { name: 'Radians → Degrees',      formula: 'degrees = radians × 180/π',                   use: 'Multiply radians by 180/π to convert',                  example: '3π/4 × 180/π = 135°' },
    { name: 'Key Radian Equivalents', formula: '30°=π/6 | 45°=π/4 | 60°=π/3\n90°=π/2 | 180°=π | 270°=3π/2 | 360°=2π', use: 'Memorise all seven — they appear in every radian question' },
    { name: 'Arc Length',             formula: 's = rθ  (θ in radians)',                      use: 'Length of an arc cut by angle θ in a circle of radius r', example: 'r=6, θ=π/3 → s=6×π/3=2π cm' },
    { name: 'Sector Area',            formula: 'A = ½r²θ  (θ in radians)',                    use: 'Area of a sector cut by angle θ in a circle of radius r', example: 'r=4, θ=π/2 → A=½×16×π/2=4π cm²' },
    { name: 'Arc/Sector Comparison',  formula: 'Radians: s=rθ, A=½r²θ\nDegrees: s=θ/360×2πr, A=θ/360×πr²', use: 'Use whichever formula matches the angle units given' },
    { name: 'Find angle from arc',    formula: 'θ = s/r  (result in radians)',                use: 'Rearranged arc formula — find the angle when arc length and radius known', example: 's=3π, r=9 → θ=3π/9=π/3 rad' },
  ],

  'age16-calculus': [
    { name: 'First Principles Definition', formula: "f'(x) = lim[h→0] (f(x+h) − f(x)) / h", use: 'Derive the derivative from scratch — required for Paper 1 proof questions' },
    { name: 'Binomial (x+h)²',      formula: '(x+h)² = x² + 2xh + h²',                      use: 'Expand before substituting into first principles formula' },
    { name: 'Binomial (x+h)³',      formula: '(x+h)³ = x³ + 3x²h + 3xh² + h³',              use: 'Expand (x+h)³ for first principles with f(x) = x³',    example: 'Coefficients: Pascal row 1-3-3-1' },
    { name: 'Power Rule',            formula: 'd/dx(xⁿ) = nxⁿ⁻¹',                            use: 'Differentiate any power of x',                          example: 'd/dx(x⁴) = 4x³' },
    { name: 'Constant × Power',      formula: 'd/dx(axⁿ) = a·n·xⁿ⁻¹',                        use: 'Coefficient multiplies by the power',                   example: 'd/dx(3x²) = 6x' },
    { name: 'Sum Rule',              formula: 'd/dx(f + g) = f\' + g\'',                      use: 'Differentiate each term separately',                    example: 'y=x³+5x → dy/dx=3x²+5' },
    { name: 'Constant Rule',         formula: 'd/dx(c) = 0',                                  use: 'Constants always differentiate to zero',                example: 'd/dx(7) = 0' },
    { name: 'Gradient at a Point',   formula: 'Gradient = dy/dx evaluated at x = a',          use: 'Differentiate, then substitute the x-value',           example: 'y=x²+3x → dy/dx=2x+3 → at x=2: gradient=7' },
    { name: 'Notation',              formula: "f'(x) = dy/dx = d/dx[f(x)]",                   use: 'Three notations all mean the same thing — the derivative' },
  ],

  'age16-exponential': [
    { name: 'Exponential Growth',    formula: 'A = P(1 + r/100)ⁿ',                           use: 'Compound growth: P = initial, r = % rate, n = periods', example: 'R2000 at 10% for 3 years: A=2000(1.1)³=2662' },
    { name: 'Exponential Decay',     formula: 'A = P(1 − r/100)ⁿ',                           use: 'Compound depreciation or decay at rate r% per period',  example: 'R10000 at 15% for 2 years: A=10000(0.85)²=7225' },
    { name: 'Half-Life Formula',     formula: 'A = P × (0.5)ⁿ  where n = time ÷ half-life', use: 'Radioactive decay — find mass after n half-life periods', example: '400g, half-life=5yr, after 10yr: n=2, A=400×(0.5)²=100g' },
    { name: 'Powers of 2',           formula: '2¹=2  2²=4  2³=8  2⁴=16  2⁵=32',             use: 'Powers of 2 appear in half-life, binary, and sequences — memorise to 2⁵' },
    { name: 'Powers of 3',           formula: '3¹=3  3²=9  3³=27  3⁴=81',                   use: 'Powers of 3 appear in sequences and geometric problems' },
    { name: 'Growth vs Decay',       formula: 'Growth: multiplier > 1 (e.g. 1.1)\nDecay: multiplier < 1 (e.g. 0.85)', use: 'Identify the type of exponential function from the multiplier' },
  ],

  'age16-algebra3': [
    { name: 'Factor Theorem',        formula: '(x − a) is a factor of f(x) iff f(a) = 0',    use: 'Test whether a linear expression is a factor; also find unknown coefficients', example: 'f(2) = 0 → (x − 2) is a factor' },
    { name: 'Remainder Theorem',     formula: 'Remainder when f(x) ÷ (x − a) = f(a)',        use: 'Find the remainder without doing long division',        example: 'f(1) = 5 → remainder is 5 when dividing by (x − 1)' },
    { name: 'Sign Rule for Roots',   formula: '(x − a): substitute x = +a\n(x + a): substitute x = −a', use: 'The root is always the OPPOSITE sign to what is inside the factor' },
    { name: 'Cubic Factorisation',   formula: 'Step 1: find one factor by factor theorem\nStep 2: divide → quadratic\nStep 3: factorise quadratic', use: 'Fully factorise a cubic polynomial', example: 'x³−6x²+11x−6 = (x−1)(x−2)(x−3)' },
    { name: 'Log Definition',        formula: 'logₐ(x) = n  ⟺  aⁿ = x',                    use: 'Convert between log and exponential form',              example: 'log₂(8) = 3 because 2³ = 8' },
    { name: 'Log Product Law',       formula: 'logₐ(mn) = logₐ(m) + logₐ(n)',               use: 'Combine logs being added — multiply their arguments',   example: 'log₂(x) + log₂(3) = log₂(3x)' },
    { name: 'Log Quotient Law',      formula: 'logₐ(m/n) = logₐ(m) − logₐ(n)',              use: 'Combine logs being subtracted — divide their arguments', example: 'log₃(x) − log₃(2) = log₃(x/2)' },
    { name: 'Log Power Law',         formula: 'logₐ(mⁿ) = n · logₐ(m)',                     use: 'Bring exponents in front as coefficients',              example: 'log₂(x³) = 3·log₂(x)' },
    { name: 'Change of Base',        formula: 'logₐ(b) = log(b) / log(a)',                   use: 'Evaluate any logarithm using a calculator (base 10 or e)', example: 'log₅(125) = log(125)/log(5) = 3' },
    { name: 'Equal Bases',           formula: 'aˣ = aⁿ  →  x = n',                           use: 'Solve exponential equations when both sides share the same base', example: '4^x = 64 → 4^x = 4³ → x = 3' },
  ],

  'age16-functions2': [
    { name: 'Hyperbola Standard Form', formula: 'y = a/(x − p) + q',                         use: 'The standard form of a hyperbolic function with shifted asymptotes' },
    { name: 'Vertical Asymptote',    formula: 'Set denominator = 0 → x = p',                 use: 'The x-value where the function is undefined',          example: 'y=2/(x−3)+1 → vertical asymptote x = 3' },
    { name: 'Horizontal Asymptote',  formula: 'y = q  (the constant added outside)',          use: 'The y-value the function approaches as x → ±∞',        example: 'y=2/(x−3)+1 → horizontal asymptote y = 1' },
    { name: 'Domain of Hyperbola',   formula: 'x ∈ ℝ, x ≠ p',                               use: 'All real x except the vertical asymptote value' },
    { name: 'Range of Hyperbola',    formula: 'y ∈ ℝ, y ≠ q',                               use: 'All real y except the horizontal asymptote value' },
    { name: 'Transformation Left',   formula: 'y = f(x + a): shift LEFT a units  (a > 0)',   use: 'Replacing x with (x + a) — counter-intuitively shifts LEFT',  example: '1/(x+2): move graph 2 left' },
    { name: 'Transformation Right',  formula: 'y = f(x − a): shift RIGHT a units  (a > 0)',  use: 'Replacing x with (x − a) shifts RIGHT' },
    { name: 'Inverse Function',      formula: 'To find f⁻¹: write y=f(x), swap x↔y, solve for y', use: 'The inverse undoes the original function',       example: 'f(x)=x²+3 (x≥0) → f⁻¹(x)=√(x−3)' },
    { name: 'Domain of Inverse',     formula: 'Domain of f⁻¹ = Range of f',                  use: 'The input of the inverse is the output of the original', example: 'f:x≥0 gives range≥3 → domain of f⁻¹ is x≥3' },
    { name: 'One-to-One Test',       formula: 'Horizontal line test: each y-value hit at most once', use: 'Check whether a function has an inverse before finding it' },
    { name: 'Exponential Inverse',   formula: 'Inverse of y = aˣ  is  y = logₐ(x)',          use: 'Exponential and logarithm are inverse functions',      example: 'h(x)=3^x → h⁻¹(x)=log₃(x)' },
    { name: 'Inverse of √x',         formula: 'f(x)=√(x−a) → f⁻¹(x)=x²+a  (domain x≥0)',   use: 'Squaring undoes the square root; restrict domain to x≥0 (range of f)' },
  ],

  'age16-analytical-geo': [
    { name: 'Point-Slope Form',      formula: 'y − y₁ = m(x − x₁)',                          use: 'Find equation of line given gradient m and one point (x₁, y₁)', example: 'm=3, point (1,−2) → y=3x−5' },
    { name: 'Slope-Intercept Form',  formula: 'y = mx + c',                                   use: 'Read gradient m and y-intercept c directly from the equation' },
    { name: 'Inclination Formula',   formula: 'm = tan(θ)  so  θ = tan⁻¹(m)',               use: 'Convert between gradient and inclination angle',        example: 'm=√3 → θ=60°;  θ=135° → m=−1' },
    { name: 'Exact Inclinations',    formula: 'θ=30° → m=√3/3\nθ=45° → m=1\nθ=60° → m=√3\nθ=135° → m=−1\nθ=120° → m=−√3', use: 'No-calculator inclination values using exact trig' },
    { name: 'Perpendicular Gradient',formula: 'm₁ × m₂ = −1  →  m₂ = −1/m₁',               use: 'Find the gradient of a line perpendicular to a given line', example: 'm=2 → m⊥=−1/2;  m=3/4 → m⊥=−4/3' },
    { name: 'Parallel Gradient',     formula: 'Parallel lines have equal gradients: m₁ = m₂', use: 'Two lines are parallel if and only if their gradients are equal' },
    { name: 'Collinearity',          formula: 'Points A, B, C collinear if m_AB = m_BC',      use: 'Prove three points lie on the same straight line',      example: 'If gradient AB = gradient BC, all three are collinear' },
    { name: 'Position Vector',       formula: 'AB⃗ = B − A  (subtract starting point)',       use: 'Find the vector from point A to point B',              example: 'A=(3,1), B=(7,5) → AB⃗=(4,4)' },
    { name: 'Vector Magnitude',      formula: '|v| = √(x² + y²)',                             use: 'Length/magnitude of a 2D vector (x, y)',               example: 'v=(−5,12) → |v|=√(25+144)=13' },
    { name: 'Unit Vector',           formula: 'v̂ = v / |v|  (divide each component by magnitude)', use: 'A vector of length 1 in the same direction as v', example: 'v=(3,4), |v|=5 → v̂=(3/5, 4/5)' },
    { name: 'Dot Product',           formula: 'a⃗ · b⃗ = x₁x₂ + y₁y₂',                     use: 'Multiply matching components and sum them',            example: '(2,3)·(3,−2) = 6−6 = 0' },
    { name: 'Perpendicular Vectors', formula: 'a⃗ ⊥ b⃗  iff  a⃗ · b⃗ = 0',                  use: 'Test if two vectors are at right angles',               example: '(2,3)·(3,−2)=0 → perpendicular ✓' },
  ],

  'age16-stats2': [
    { name: 'Mean',                  formula: 'x̄ = Σx / n',                                  use: 'Average: sum all values, divide by count' },
    { name: 'Variance (Population)', formula: 'σ² = Σ(x − x̄)² / n',                         use: 'Average of squared deviations from the mean',          example: '{2,4,4,6}: mean=4, σ²=(4+0+0+4)/4=2' },
    { name: 'Standard Deviation',    formula: 'σ = √(Σ(x − x̄)² / n)',                       use: 'Square root of variance — measures spread in original units', example: '{1..7}: mean=4, σ²=4, σ=2' },
    { name: 'SD Calculation Steps',  formula: '1. Find mean x̄\n2. Find each (x − x̄)²\n3. Variance = average of (x−x̄)²\n4. SD = √variance', use: 'Four-step process for standard deviation' },
    { name: 'SD Interpretation',     formula: 'Smaller SD → more consistent (clustered near mean)\nLarger SD → more spread (variable)', use: 'Compare consistency of two data sets with the same mean' },
    { name: '1 SD Interval',         formula: 'mean − σ  to  mean + σ',                      use: 'The interval within 1 standard deviation of the mean', example: 'mean=10, σ=3 → interval 7 to 13' },
    { name: 'Conditional Probability', formula: 'P(A | B) = P(A ∩ B) / P(B)',               use: 'Probability of A given B has already occurred',        example: 'P(A∩B)=0.12, P(B)=0.4 → P(A|B)=0.3' },
    { name: 'Independence Test',     formula: 'A and B independent iff P(A∩B) = P(A)×P(B)', use: 'Check whether two events influence each other',        example: 'P(A)=0.3, P(B)=0.5, P(A∩B)=0.15=0.3×0.5 → independent' },
    { name: 'Without Replacement',   formula: 'P(2nd | 1st occurred): reduce numerator AND denominator by 1', use: 'Dependent draws — first outcome changes the pool for the second', example: '4 red/10: P(both red) = 4/10 × 3/9 = 2/15' },
    { name: 'Complement Rule',       formula: "P(A') = 1 − P(A)",                            use: 'Probability of event NOT occurring' },
  ],
  // ── Age 17 — School of Thinkers (A-Level Pure / CAPS Gr 12) ────────────────
  'age17-diff': [
    { name: 'Power Rule',            formula: 'd/dx(xⁿ) = n·xⁿ⁻¹',                          use: 'Differentiate any power term',                          example: 'd/dx(x⁵) = 5x⁴' },
    { name: 'Chain Rule',            formula: 'd/dx f(g(x)) = f′(g(x))·g′(x)',                use: 'Differentiate a function of a function',                example: 'd/dx(3x+1)⁴ = 4(3x+1)³·3 = 12(3x+1)³' },
    { name: 'Product Rule',          formula: '(uv)′ = u′v + uv′',                            use: 'Differentiate a product of two functions',              example: 'd/dx[x²(x+1)] = 2x(x+1)+x²' },
    { name: 'Quotient Rule',         formula: '(u/v)′ = (u′v − uv′)/v²',                      use: 'Differentiate a quotient of two functions' },
    { name: 'Second Derivative',     formula: "f″(x) = d/dx(f′(x))",                          use: 'Differentiate twice — tests concavity / nature of stationary point' },
    { name: 'Stationary Points',     formula: "Solve f′(x) = 0",                              use: 'Maxima, minima or inflection where gradient = 0' },
    { name: 'Nature Test',           formula: "f″(x) > 0 → min · f″(x) < 0 → max",            use: 'Classify a stationary point using the second derivative' },
  ],
  'age17-int': [
    { name: 'Power Rule (Integral)', formula: '∫xⁿ dx = xⁿ⁺¹/(n+1) + C',                     use: 'Reverse of differentiation (n ≠ −1)',                   example: '∫x³ dx = x⁴/4 + C' },
    { name: 'Definite Integral',     formula: '∫ₐᵇ f(x) dx = F(b) − F(a)',                    use: 'Evaluate between limits — no constant C',               example: '∫₀² 2x dx = [x²]₀² = 4' },
    { name: 'Area Under Curve',      formula: 'Area = ∫ₐᵇ y dx',                              use: 'Area between curve and x-axis from a to b' },
    { name: 'Reverse Chain',         formula: '∫(ax+b)ⁿ dx = (ax+b)ⁿ⁺¹/[a(n+1)] + C',         use: 'Integrate a linear bracket raised to a power',          example: '∫(2x+1)³ dx = (2x+1)⁴/8 + C' },
    { name: 'Sum Rule',              formula: '∫[f(x)±g(x)] dx = ∫f ± ∫g',                    use: 'Integrate term by term' },
  ],
  'age17-series': [
    { name: 'Arithmetic nth Term',   formula: 'Tₙ = a + (n−1)d',                              use: 'a = first term, d = common difference' },
    { name: 'Arithmetic Sum',        formula: 'Sₙ = n/2[2a + (n−1)d]',                        use: 'Sum of first n terms',                                  example: 'a=2,d=3,n=5 → 5/2(4+12)=40' },
    { name: 'Geometric nth Term',    formula: 'Tₙ = a·rⁿ⁻¹',                                  use: 'r = common ratio' },
    { name: 'Geometric Sum',         formula: 'Sₙ = a(rⁿ−1)/(r−1)',                           use: 'Sum of first n terms (r ≠ 1)',                          example: 'a=3,r=2,n=4 → 3(15)=45' },
    { name: 'Sum to Infinity',       formula: 'S∞ = a/(1−r),  |r| < 1',                       use: 'Converges only when the ratio is between −1 and 1',     example: 'a=8,r=½ → 8/(1−½)=16' },
    { name: 'Sigma Notation',        formula: 'Σ from r=1 to n of Tᵣ',                        use: 'Compact sum notation — substitute and add' },
  ],
  'age17-trig3': [
    { name: 'Identity',              formula: 'sin²θ + cos²θ = 1',                            use: 'Convert between sin and cos' },
    { name: 'tan Identity',          formula: 'tanθ = sinθ / cosθ',                           use: 'Rewrite tan in terms of sin and cos' },
    { name: 'Compound Angle (sin)',  formula: 'sin(A±B) = sinA cosB ± cosA sinB',             use: 'Expand a sum or difference of angles' },
    { name: 'Compound Angle (cos)',  formula: 'cos(A±B) = cosA cosB ∓ sinA sinB',             use: 'Note the sign swap on the right' },
    { name: 'Exact Values',          formula: 'sin30=½ · cos30=√3/2 · tan45=1',               use: 'Special angles in degrees / radians' },
    { name: 'Radians',               formula: 'π rad = 180°',                                 use: 'Convert: multiply degrees by π/180' },
  ],
  'age17-logexp': [
    { name: 'Product Law',           formula: 'log a + log b = log(ab)',                      use: 'Combine logs of the same base' },
    { name: 'Quotient Law',          formula: 'log a − log b = log(a/b)',                     use: 'Subtract logs of the same base' },
    { name: 'Power Law',             formula: 'log(aⁿ) = n·log a',                            use: 'Bring an exponent down as a coefficient' },
    { name: 'ln & e',                formula: 'ln(eˣ) = x,  e^(ln x) = x',                    use: 'Natural log and exp are inverses' },
    { name: 'Solve Exponential',     formula: 'aˣ = b → x = ln b / ln a',                     use: 'Take logs of both sides',                               example: '2ˣ=8 → x=ln8/ln2=3' },
    { name: 'Change of Base',        formula: 'log_b x = ln x / ln b',                        use: 'Evaluate a log to any base with a calculator' },
  ],
  'age17-func3': [
    { name: 'Composite Function',    formula: 'fg(x) = f(g(x))',                              use: 'Apply g first (inner), then f (outer)' },
    { name: 'Inverse Function',      formula: 'Swap x & y, solve for y',                      use: 'f⁻¹ undoes f',                                          example: 'f(x)=2x+3 → f⁻¹(x)=(x−3)/2' },
    { name: 'Modulus Equation',      formula: '|x| = a → x = a or x = −a  (a ≥ 0)',           use: 'Two cases for an absolute-value equation' },
    { name: 'Domain',                formula: 'Valid inputs x',                               use: 'Exclude ÷0 and √negative' },
    { name: 'Range',                 formula: 'Possible outputs f(x)',                        use: 'For y=x²+c the range is y ≥ c' },
  ],
  'age17-algebra4': [
    { name: 'Partial Fractions',     formula: 'P(x)/[(x+a)(x+b)] = A/(x+a) + B/(x+b)',        use: 'Split a single fraction into simpler ones' },
    { name: 'Cover-Up Rule',         formula: 'A = value of remaining fraction at x = −a',    use: 'Quick way to find each numerator constant' },
    { name: 'Binomial Coefficient',  formula: 'ⁿCᵣ = n! / [r!(n−r)!]',                        use: 'Count combinations / term coefficients',                example: '⁵C₂ = 120/(2·6) = 10' },
    { name: 'Binomial Theorem',      formula: '(a+b)ⁿ = Σ ⁿCᵣ aⁿ⁻ʳ bʳ',                       use: 'Expand a bracket raised to a power' },
    { name: 'Factor Theorem',        formula: 'If f(k)=0 then (x−k) is a factor',             use: 'Find a root to factorise a cubic' },
  ],
};
